language: r
r: bioc-release
compiler:
  - gcc

r_github_packages: gtonkinhill/rhierbaps

cache: packages

warnings_are_errors: false

sudo: required



notifications:
    slack: pathogens:8NUkMUXlMNecj9NXnwTKbBQU



matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"



before_install:
    - eval "${MATRIX_EVAL}"

before_install:
  - sudo apt-get install libgmp3-dev
  # Link gcc-6 and g++-6 to their standard commands
  - ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - ln -s /usr/bin/g++-7 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version

# Specify local Makevars configuration
before_install:
  - mkdir -p ~/.R
  - VER=-7
  - echo "CC=gcc$(VER) -std=gnu99" >> ~/.R/Makevars
  - echo "CXX=g++$(VER)"           >> ~/.R/Makevars
  - echo 'CXX1X=$(CXX)'            >> ~/.R/Makevars
  - echo 'CXX11=$(CXX)'            >> ~/.R/Makevars
  - echo 'CXX14=$(CXX)'            >> ~/.R/Makevars
  - echo 'CXX14=$(CXX)'            >> ~/.R/Makevars
  - echo "SHLIB_CXXLD=g++$(VER)"   >> ~/.R/Makevars
  - echo "FC=gfortran$(VER)"       >> ~/.R/Makevars
  - echo "F77=gfortran$(VER)"      >> ~/.R/Makevars
  - echo "CFLAGS=-mtune=native -g -O2 -Wall -pedantic -Wconversion"      >> ~/.R/Makevars
  - echo "CXXFLAGS=-mtune=native -g -O2 -Wall -pedantic -Wconversion"      >> ~/.R/Makevars
