language: r
r: bioc-release

r_github_packages: gtonkinhill/rhierbaps

cache: packages

compiler:
  - gcc

warnings_are_errors: false

sudo: required

before_install: sudo apt-get install libgmp3-dev

notifications:
    slack: pathogens:8NUkMUXlMNecj9NXnwTKbBQU


before_install:

  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-7
  - sudo apt-get -qq install g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo apt-get install libgfortran3
  - sudo apt-get install r-base-dev
  - sudo apt-get install libarmadillo-dev
  - sudo apt-get install libopenblas-dev
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install libarpack++2-dev
  - sudo apt-get install gfortran
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/libgfortran.so
  - sudo apt-get -qq update


r_packages:
  - devtools
  - roxygen2
  - testthat
  - knitr
  - rmarkdown
  - Rcpp
  - RcppArmadillo
