language: r
r: bioc-release

r_github_packages: gtonkinhill/rhierbaps

cache: packages

warnings_are_errors: false

sudo: required

notifications:
    slack: pathogens:8NUkMUXlMNecj9NXnwTKbBQU


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install: |
  sudo apt-get install libgmp3-dev
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11

