dist: trusty
language: r
r: bioc-release

r_github_packages: gtonkinhill/rhierbaps

cache: packages

warnings_are_errors: false

sudo: required

before_install: sudo apt-get install libgmp3-dev

notifications:
    slack: pathogens:8NUkMUXlMNecj9NXnwTKbBQU



matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
